setup_swagger_drf
KirillYabl/MyCityBackend pull request #4
Opened 2023-02-24 07:50 UTC by LVVS666

2023-02-24 12:51 UTC, KirillYabl requested changes

2023-02-24 12:51 UTC, KirillYabl commented on my_city/my_city/settings.py
> +    'drf_yasg',
для красоты предложу, что сначал перечислены базовые приложения джанги, потом строка отступа и потом установленные, потом строка отступа и наши
Если flake8 разрешает отступы, если не ращрешает, то без них

2023-02-24 12:51 UTC, KirillYabl commented on my_city/my_city/urls.py
> +urlpatterns += [
Давай строчки из этого urlpatterns просто перечислим в том, заечм здесь еще через +=, немного как нагромождение кажется выглядит

2023-02-24 14:50 UTC, LVVS666 commented on my_city/my_city/urls.py
> +urlpatterns += [
кстати изначально сделал как ты сказал,а потом в доке увидел именно так)

2023-02-25 06:26 UTC, KirillYabl approved these changes

2023-02-25 06:26 UTC, merged