jwt_auth
KirillYabl/MyCityBackend pull request #7
Opened 2023-03-06 16:12 UTC by LVVS666

2023-03-06 19:23 UTC, KirillYabl requested changes

2023-03-06 19:23 UTC, KirillYabl commented on my_city/my_city/urls.py
> -    path('api-auth/', include('rest_framework.urls')),
зачем удалять этот url? он же помогает в разработке

2023-03-06 19:23 UTC, KirillYabl commented on my_city/my_city/urls.py
> +    path('api/', include('user_app.urls')),
давай может api/users/ ? Еще же в приложении квеста будут урлы, а они тоже апи

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/admin.py
> +class CustomUserAdmin(UserAdmin):
между импортами пробелы, прогонял через flake8?

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/admin.py
> +class CustomUserAdmin(UserAdmin):
Зачем эта приставка "Custom"? Весь созданный нами код будет кастомным, она информации не добавляет

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/admin.py
> +admin.site.register(CustomUser, CustomUserAdmin)
Лучше декоратор использовать, так точно не забудешь зарегистрировать

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/forms.py
> +class CustomUserCreationForm(UserCreationForm):
Зачем эта приставка "Custom"? Весь созданный нами код будет кастомным, она информации не добавляет
Здесь можно UserCreationForm под другим именем импортировать

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/forms.py
> +    class Meta(UserCreationForm):
Очень странное наследование, вряд ли оно здесь нужно

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/forms.py
> +class CustomUserChangeForm(UserChangeForm):
Зачем эта приставка "Custom"? Весь созданный нами код будет кастомным, она информации не добавляет

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/managers.py
> +class CustomUserManager(BaseUserManager):
Зачем эта приставка "Custom"? Весь созданный нами код будет кастомным, она информации не добавляет

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/managers.py
> +        if extra_fields.get('is_staff') is not True:
Может вместо этого превентивно эти поля просто True делать, которые проверяются, здесь же речь как раз о создании суперюзера

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/managers.py
> +    def create_user(self, email, password, **extra_fields):
extra_fields кажется неюезопасной штукой, получается через этот апи случайно можно суперюзера создать, чего мы не хотим

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/managers.py
> +    def create_superuser(self, email, password, **extra_fields):
Может вообще убрать это? Кажется небезопасным давать апи на такое

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/models.py
> +class CustomUser(AbstractUser):
Зачем эта приставка "Custom"? Весь созданный нами код будет кастомным, она информации не добавляет

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/forms.py
> +from .models import CustomUser
импорты разных уровней (стандартная библиотека, импортируемая библиотека, собственные модули) должны быть разделены пустой строкой

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/models.py
> +from .managers import CustomUserManager
импорты разных уровней (стандартная библиотека, импортируемая библиотека, собственные модули) должны быть разделены пустой строкой

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/serializers.py
> +from .models import CustomUser
импорты разных уровней (стандартная библиотека, импортируемая библиотека, собственные модули) должны быть разделены пустой строкой

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/urls.py
> +from .views import RegistrationAPI, LoginAPI, UserAPI
импорты разных уровней (стандартная библиотека, импортируемая библиотека, собственные модули) должны быть разделены пустой строкой

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/views.py
> +from .serializers import CreateUserSerializer, UserSerializer, LoginUserSerializer
импорты разных уровней (стандартная библиотека, импортируемая библиотека, собственные модули) должны быть разделены пустой строкой

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/serializers.py
> +        user = CustomUser.objects.create_user(validated_data['email'],
А зачем здесь перенос строки? все же вроде помещается

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/views.py
> +            "token": AuthToken.objects.create(user)[1]
предлагаю не писать в индексах числа, а перед этим задать переменную, что значит эта единичка, типо видимо это token_index, а то так не очень понятно, что там

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/views.py
> +            "token": AuthToken.objects.create(user)[1]
предлагаю не писать в индексах числа, а перед этим задать переменную, что значит эта единичка, типо видимо это token_index, а то так не очень понятно, что там

2023-03-06 19:23 UTC, KirillYabl commented on my_city/user_app/views.py
> +            "user": UserSerializer(user, context=self.get_serializer_context()).data,
я вот здесь не понял, вернет не то же самое, что и в serializer.validated_data?

2023-03-11 07:49 UTC, KirillYabl requested changes

2023-03-11 07:49 UTC, KirillYabl commented on my_city/user_app/admin.py
> +    ordering = ('email',)
А если все это убрать, что-то поменяется? это не наследуется из родительского класса?

2023-03-11 07:49 UTC, KirillYabl commented on my_city/user_app/admin.py
> +admin.site.register(User, UserAdmin)
давай через декоратора регистрации админ моделей делать, @admin.register(User) над классом админки

2023-03-11 07:49 UTC, KirillYabl commented on my_city/user_app/views.py
> +from my_city.settings import TOKEN_INDEX
1. settings лучше импортировать как from django.conf import settings
2. кажется это переменная не настолько глобальная, чтобы ее в настройках задавать, я бы предложил ее задавать в отдельных функциях маленьким регистром

2023-03-11 07:49 UTC, KirillYabl commented on my_city/user_app/views.py
> +        if check_password(request.POST['password'], user.password):
а не лучше это перенести в валидацию сериалайзера? Если пароль неверный для пользователя, то это ошибка валидации

2023-03-11 07:49 UTC, KirillYabl commented on my_city/user_app/views.py
> +        user = User.objects.get(email=serializer.data['email'])
Здесь если неверный email, то будет 500 ошибка, а должна быть 404, для этого в джанге есть шорткат get_object_or_404

2023-03-11 07:49 UTC, KirillYabl commented on my_city/user_app/views.py
> +        else:
т.к. в if ты делаешь return, то здесь else уже бессмысленный, то что в нем просто можно левее перенести

2023-03-11 07:49 UTC, KirillYabl commented on my_city/user_app/views.py
> +            return Response('Неверный пароль!')
Получается ответ со статусом 200, как-то странно

2023-03-11 07:49 UTC, KirillYabl commented on my_city/user_app/serializers.py
> +class CreateUserSerializer(serializers.ModelSerializer):
а сложность введенного пароля где-то проверяется?

2023-03-11 07:49 UTC, KirillYabl commented on my_city/user_app/serializers.py
> +class CreateUserSerializer(serializers.ModelSerializer):
имея ввиду, что это отнаследовалось от модели?

2023-03-15 14:21 UTC, LVVS666 commented on my_city/my_city/urls.py
> +    path('api/', include('user_app.urls')),
+

2023-03-15 14:21 UTC, LVVS666 commented on my_city/user_app/admin.py
> +class CustomUserAdmin(UserAdmin):
+

2023-03-15 14:22 UTC, LVVS666 commented on my_city/user_app/serializers.py
> +class CreateUserSerializer(serializers.ModelSerializer):
+

2023-03-15 14:22 UTC, LVVS666 commented on my_city/user_app/views.py
> +            return Response('Неверный пароль!')
+

2023-03-15 14:22 UTC, LVVS666 commented on my_city/user_app/views.py
> +        else:
+

2023-03-15 14:23 UTC, LVVS666 commented on my_city/user_app/views.py
> +        user = User.objects.get(email=serializer.data['email'])
+

2023-03-15 14:23 UTC, LVVS666 commented on my_city/user_app/views.py
> +        if check_password(request.POST['password'], user.password):
+

2023-03-15 14:23 UTC, LVVS666 commented on my_city/user_app/views.py
> +from my_city.settings import TOKEN_INDEX
+

2023-03-15 14:23 UTC, LVVS666 commented on my_city/user_app/admin.py
> +admin.site.register(User, UserAdmin)
+

2023-03-15 14:24 UTC, LVVS666 commented on my_city/user_app/admin.py
> +    ordering = ('email',)
часть убрал

2023-03-15 14:24 UTC, LVVS666 commented on my_city/user_app/views.py
> +            "user": UserSerializer(user, context=self.get_serializer_context()).data,
+

2023-03-15 14:25 UTC, LVVS666 commented on my_city/user_app/views.py
> +            "token": AuthToken.objects.create(user)[1]
+

2023-03-15 15:29 UTC, KirillYabl requested changes

2023-03-15 15:29 UTC, KirillYabl commented on my_city/user_app/models.py
> +max_length = 20
мне кажется лучше эти две переменные перенести в класс, или назвать так, чтобы было понятно о чем они, например min_password_length, потому что если здесь будут другие модели (а они будут), то не понятно, что за длина

2023-03-15 15:29 UTC, KirillYabl commented on my_city/user_app/models.py
> +                              validators=(MinLengthValidator(min_length), MaxLengthValidator(max_length),),
а почему валидаторы у емайла? У пароля же вроде хотел?

2023-03-15 15:29 UTC, KirillYabl commented on my_city/user_app/serializers.py
> +        user = authenticate(password=password)
эта строчка точно работает? Как она понимает пользователя чисто по паролю (без емейла)? Или я что-то не понимаю?

2023-03-16 00:15 UTC, LVVS666 commented on my_city/user_app/serializers.py
> +        user = authenticate(password=password)
добавил email

2023-03-16 00:18 UTC, LVVS666 commented on my_city/user_app/models.py
> +max_length = 20
исправил

2023-03-16 00:18 UTC, LVVS666 commented on my_city/user_app/models.py
> +                              validators=(MinLengthValidator(min_length), MaxLengthValidator(max_length),),
исправил

2023-03-16 05:44 UTC, KirillYabl commented on my_city/user_app/managers.py
> +    def create_superuser(self, email, password, **extra_fields):
это для createsuperuser

2023-03-16 05:48 UTC, KirillYabl approved these changes

2023-03-16 05:48 UTC, merged